# Generated by Django 4.2.30 on 2026-06-10 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sin título', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('width', models.IntegerField(default=1200)),
                ('height', models.IntegerField(default=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dibujo',
                'verbose_name_plural': 'Dibujos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Capa 1', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('opacity', models.FloatField(default=1.0)),
                ('visible', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='canvas.drawing')),
            ],
            options={
                'verbose_name': 'Capa',
                'verbose_name_plural': 'Capas',
                'ordering': ['order'],
            },
        ),
    ]
